In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("sales_data.csv")
df

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,03-02-2023,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,21-04-2023,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,21-09-2023,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,24-08-2023,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,24-03-2023,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1010,15-04-2023,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,07-09-2023,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,27-04-2023,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,20-12-2023,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,16-08-2023,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   object
 2   Sales_Rep             1000 non-null   object
 3   Region                1000 non-null   object
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   object
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object
 12  Sales_Channel         1000 non-null   object
 13  Region_and_Sales_Rep  1000 non-null   object
dtypes: float64(4), int64(2), object(8)
memory usage: 109.5+ KB

In [6]:
df.isnull().sum()

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64

In [7]:
df.describe()

,Product_ID,Sales_Amount,Quantity_Sold,Unit_Cost,Unit_Price,Discount
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,1050.128000,5019.265230,25.355000,2475.304550,2728.440120,0.15239
std,29.573505,2846.790126,14.159006,1417.872546,1419.399839,0.08720
min,1001.000000,100.120000,1.000000,60.280000,167.120000,0.00000
25%,1024.000000,2550.297500,13.000000,1238.380000,1509.085000,0.08000
50%,1051.000000,5019.300000,25.000000,2467.235000,2696.400000,0.15000
75%,1075.000000,7507.445000,38.000000,3702.865000,3957.970000,0.23000
max,1100.000000,9989.040000,49.000000,4995.300000,5442.150000,0.30000

In [8]:
 df.describe(include = 'all')

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
count,1000.000000,1000,1000,1000,1000.000000,1000.000000,1000,1000.000000,1000.000000,1000,1000.00000,1000,1000,1000
unique,NaN,340,5,4,NaN,NaN,4,NaN,NaN,2,NaN,3,2,20
top,NaN,14-11-2023,David,North,NaN,NaN,Clothing,NaN,NaN,New,NaN,Credit Card,Retail,North-Eve
freq,NaN,8,222,267,NaN,NaN,268,NaN,NaN,504,NaN,345,512,64
mean,1050.128000,NaN,NaN,NaN,5019.265230,25.355000,NaN,2475.304550,2728.440120,NaN,0.15239,NaN,NaN,NaN
std,29.573505,NaN,NaN,NaN,2846.790126,14.159006,NaN,1417.872546,1419.399839,NaN,0.08720,NaN,NaN,NaN
min,1001.000000,NaN,NaN,NaN,100.120000,1.000000,NaN,60.280000,167.120000,NaN,0.00000,NaN,NaN,NaN
25%,1024.000000,NaN,NaN,NaN,2550.297500,13.000000,NaN,1238.380000,1509.085000,NaN,0.08000,NaN,NaN,NaN
50%,1051.000000,NaN,NaN,NaN,5019.300000,25.000000,NaN,2467.235000,2696.400000,NaN,0.15000,NaN,NaN,NaN
75%,1075.000000,NaN,NaN,NaN,7507.445000,38.000000,NaN,3702.865000,3957.970000,NaN,0.23000,NaN,NaN,NaN
max,1100.000000,NaN,NaN,NaN,9989.040000,49.000000,NaN,4995.300000,5442.150000,NaN,0.30000,NaN,NaN,NaN

In [10]:
df.columns

Index(['Product_ID', 'Sale_Date', 'Sales_Rep', 'Region', 'Sales_Amount',
       'Quantity_Sold', 'Product_Category', 'Unit_Cost', 'Unit_Price',
       'Customer_Type', 'Discount', 'Payment_Method', 'Sales_Channel',
       'Region_and_Sales_Rep'],
      dtype='object')

In [11]:
df.columns = df.columns.str.lower()

In [12]:
df.columns

Index(['product_id', 'sale_date', 'sales_rep', 'region', 'sales_amount',
       'quantity_sold', 'product_category', 'unit_cost', 'unit_price',
       'customer_type', 'discount', 'payment_method', 'sales_channel',
       'region_and_sales_rep'],
      dtype='object')

In [13]:
df.to_excel("cleaned_sales_data.xlsx", index=False)